export const RECEPCION_DNAC = 1
export const EVALUACION = 2
export const FIRMA_SELLO_DIR_NAC = 3
export const CONFORMIDAD_SUB_DIREC_NAC = 4
export const CONFORMIDAD_DIREC_NAC = 5

export const RECEPCION_DNAC_NAME = 'RECEPCIÓN DNAC'
export const EVALUACION_NAME = 'EVALUACIÓN'
export const FIRMA_SELLO_DIR_NAC_NAME = 'FIRMA SELLO DIRECCIÓN NAC'
export const CONFORMIDAD_SUB_DIREC_NAC_NAME = 'CONFORMIDAD SUB DIRECCIÓN NACIOINALIZACIÓN'
export const CONFORMIDAD_DIREC_NAC_NAME = 'CONFORMIDAD DIRECCIÓN NACIONALIZACIÓN'

export const etapas = [
   {step: RECEPCION_DNAC, title: RECEPCION_DNAC_NAME},
   {step: EVALUACION, title: EVALUACION_NAME},
   {step: FIRMA_SELLO_DIR_NAC, title: FIRMA_SELLO_DIR_NAC_NAME},
   {step: CONFORMIDAD_SUB_DIREC_NAC, title: CONFORMIDAD_SUB_DIREC_NAC_NAME},
   {step: CONFORMIDAD_DIREC_NAC, title: CONFORMIDAD_DIREC_NAC_NAME},
]